apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: af0mmmxl5-go
  janus-idp.io/tekton: af0mmmxl5-go
  backstage.io/kubernetes-id: af0mmmxl5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: af0mmmxl5-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
